### PR TITLE
Button component

### LINKED ISSUE #2: Create a shared button
**What's wrong**
- We are reusing and restyling the MUI button over and over again. This can cause many minor differences between buttons.  

**What done looks like**
- We need to create a button that can take in a "type" property which will determine the styling for the button.  The button will need to have any information it holds passed into it so it can be reused and replace all other buttons.  

**Where the changes need to be made**
- Anywhere we are currently using an MUI Button component

please name this 
PSAButton.jsx

### PR DESCRIPTION
**Pull request by nisarg210**
Button Component 

- Added Button component for input functionality.

### CODE REVIEW

File: src/button/button.jsx [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+    color: selected ? 'white' : '#8abc62',
+    border: '10px',
+    '&:hover': {
+      backgroundColor: selected ? '#598444' : 'white',
+      color: selected ? 'white' : '#8abc62',
+    },
+  }),
+}));
+
+export function PSAButton({
```
Comment (mikahpinegar) [inline src/button/button.jsx]: will you make this an arrow function?

**Comment by mikahpinegar** [comment]
please add a description to all prs

**Comment by mikahpinegar** [comment]
please link the related issue to this pr

File: src/button/button.jsx [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+      transparent={transparent}
+      onClick={onClick}
+    >
+      {title}
+    </StyledButton>
+  );
+}
+
+PSAButton.propTypes = {
+  title: PropTypes.string,
```
Comment (YazidZidane) [inline src/button/button.jsx:101]: Can you also add some descriptions for the props? You can add description in JSDoc format:
```
/**
 * Add descriptions here
 */
```
This will be shown in the story `Description` part which will have a clear instructions for these props

File: src/button/button.jsx (hunk 1 above)
Comment (nisarg210) [reply src/button/button.jsx]: Converted to Arrow Function.

File: src/button/button.jsx (hunk 2 above)
Comment (nisarg210) [reply src/button/button.jsx:101]: Added Description.
